version: '3.7'
services:
  sample-prod:
    container_name: would-you-rather
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1337:80'
#docker-compose -f docker-compose.yml up -d --build